name: build main branch

on:
  push:
    branches: [ main ]
    paths:
      - "*.py"
      - "Makefile"
  pull_request:
    branches: [ main ]
    paths:
      - "*.py"
      - "Makefile"

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install make
        run: choco install make

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Setup venv
        run: |
          python -m venv venv
          pip install -r requirements.txt

      - name: Build
        run: make
  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Setup venv
        run: |
          python -m venv venv
          pip install -r requirements.txt

      - name: Build
        run: make